import React from 'react';
import { Box, Typography, Grid, Card, CardContent, CardActions, Button } from '@mui/material';

const demoAnalyses = [
  {
    title: 'tRNA Secondary Structure',
    description: 'Classic cloverleaf structure with conserved loops and stems.',
    sequence: 'GGGCCGUAUGGCUCAGAAUAGCGGAGGUUCGAAUCCCGGCC',
    svg: (
      <svg width="80" height="60" viewBox="0 0 80 60" aria-label="tRNA structure" style={{ display: 'block', margin: '0 auto' }}>
        <ellipse cx="40" cy="30" rx="30" ry="18" fill="#e0f7fa" stroke="#00bfae" strokeWidth="2" />
        <rect x="36" y="10" width="8" height="20" fill="#00bfae" rx="4" />
        <rect x="36" y="30" width="8" height="20" fill="#00bfae" rx="4" />
      </svg>
    ),
  },
  {
    title: 'Poly-G Motif',
    description: 'G-rich sequence forming a stable G-quadruplex motif.',
    sequence: 'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    svg: (
      <svg width="80" height="60" viewBox="0 0 80 60" aria-label="Poly-G motif" style={{ display: 'block', margin: '0 auto' }}>
        <circle cx="20" cy="30" r="10" fill="#43a047" />
        <circle cx="40" cy="30" r="10" fill="#43a047" />
        <circle cx="60" cy="30" r="10" fill="#43a047" />
      </svg>
    ),
  },
  {
    title: 'AI-Designed RNA',
    description: 'A novel sequence generated by the RNA Designer model.',
    sequence: 'AUGCGUACGUAGCUAGCGUACGUAGCUAGCGUACGUAGCUA',
    svg: (
      <svg width="80" height="60" viewBox="0 0 80 60" aria-label="AI-designed RNA" style={{ display: 'block', margin: '0 auto' }}>
        <polyline points="10,50 30,10 50,50 70,10" fill="none" stroke="#00e5ff" strokeWidth="3" />
        <circle cx="10" cy="50" r="4" fill="#00e5ff" />
        <circle cx="30" cy="10" r="4" fill="#00e5ff" />
        <circle cx="50" cy="50" r="4" fill="#00e5ff" />
        <circle cx="70" cy="10" r="4" fill="#00e5ff" />
      </svg>
    ),
  },
];

export const FeaturedAnalyses: React.FC<{ onTryExample: (seq: string) => void }> = ({ onTryExample }) => (
  <Box className="section-fade" sx={{ my: 6 }}>
    <Typography variant="h4" component="h2" align="center" gutterBottom>
      Featured Analyses
    </Typography>
    <Typography variant="body1" align="center" sx={{ mb: 4 }}>
      Explore example RNA structures and motifs. Click below to try them instantly!
    </Typography>
    <Grid container={true} spacing={4} justifyContent="center">
      {demoAnalyses.map((a, i) => (
        <Box key={i} sx={{ flexBasis: { xs: '100%', sm: '50%', md: '33.33%' }, maxWidth: { xs: '100%', sm: '50%', md: '33.33%' }, flexGrow: 1, p: 1, display: 'flex' }}>
          <Card tabIndex={0} aria-label={`Featured analysis: ${a.title}`} sx={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', p: 2 }}>
            <Box sx={{ mt: 2, mb: 1 }}>{a.svg}</Box>
            <CardContent sx={{ flexGrow: 1 }}>
              <Typography variant="h6" component="h3" align="center">{a.title}</Typography>
              <Typography variant="body2" align="center" color="text.secondary">{a.description}</Typography>
            </CardContent>
            <CardActions>
              <Button variant="outlined" color="primary" onClick={() => onTryExample(a.sequence)} aria-label={`Try example: ${a.title}`}>
                Try this example
              </Button>
            </CardActions>
          </Card>
        </Box>
      ))}
    </Grid>
  </Box>
); 