name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m venv venv
      - run: . venv/bin/activate && pip install -r requirements.txt
      - run: |
          . venv/bin/activate
          if [ -f "-m unittest discover" ]; then
            python -m unittest discover || true
          fi 